# This is a basic workflow to help you get started with Actions

name: Master Branch Workflow

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  paths:
      - "/"

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  Deploy_To_Org:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    container:
      image: abhisheksaxena7/salesforcedockerimg
      options: --user 0:0 --privileged
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Validate to the org
        run: |
          ant -buildfile build/build.xml deployEmptyCheckOnly -Dsfdc.username=${{ secrets.SFDC_USERNAME }} -Dsfdc.password=${{ secrets.SFDC_PASS }} -Dsfdc.serverurl=${{ secrets.SFDC_SERVERURL }}

      # Runs a set of commands using the runners shell
      - name: Deploy to Org
        run: |
          ant -buildfile build/build.xml deployCode -Dsfdc.username=${{ secrets.SFDC_USERNAME }} -Dsfdc.password=${{ secrets.SFDC_PASS }} -Dsfdc.serverurl=${{ secrets.SFDC_SERVERURL }}
